{{- if .Values.agent.token }}
apiVersion: {{ template "deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/binarystore: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.registryCreds.gcrServiceAccountKey }}
        checksum/binarystore: {{ include (print $.Template.BasePath "/secret-gcr.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.registryCreds.dockerConfig }}
        checksum/binarystore: {{ include (print $.Template.BasePath "/secret-registry.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.registryCreds.dockerconfigjson }}
        checksum/binarystore: {{ include (print $.Template.BasePath "/secret-dockerconfigjson.yaml") . | sha256sum }}
        {{- end }}
{{- with .Values.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccount: {{ template "fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.registryCreds.dockerconfigjson }}
          imagePullSecrets:
          - name: {{ template "fullname" . }}-dockerconfigjson
          {{- end }}
{{- with .Values.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
{{- end }}
          env:
            # BUILDKITE AGENT ENV VARS
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: agent-token
            - name: BUILDKITE_AGENT_TAGS
              value: "{{ .Values.agent.tags }}"
            {{- if .Values.privateSshKey }}
            - name: SSH_PRIVATE_RSA_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: agent-ssh
            {{- end }}
            {{- if .Values.dind.enabled }}
            - name: DOCKER_HOST
              value: "tcp://localhost:{{ .Values.dind.port | default "2375" }}"
            - name: BUILDKITE_BUILD_PATH
              value: "/var/buildkite/builds"
            - name: BUILDKITE_PLUGINS_PATH
              value: "/var/buildkite/plugins"
            - name: BUILDKITE_HOOKS_PATH
              value: "/var/buildkite/hooks"
            {{- end }}
            # EXTRA BUILDKITE AGENT ENV VARS
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | nindent 12 }}
{{- end }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
{{- if .Values.volumeMounts }}{{ toYaml .Values.volumeMounts | nindent 12 }}{{- end }}
{{- if .Values.enableHostDocker }}
            - name: var-run-docker-sock
              mountPath: /var/run/docker.sock
{{- end }}
            {{- if .Values.registryCreds.gcrServiceAccountKey }}
            - name: service-key
              mountPath: /etc/service_key
            {{- end }}
            {{- if .Values.registryCreds.dockerConfig }}
            - name: docker-config
              mountPath: /root/.docker
            {{- end }}
            {{- if .Values.dind.enabled }}
            - name: shared-volume
              mountPath: "/var/buildkite"
            {{- end }}
            {{- if .Values.entrypointd }}
            - name: entrypointd
              mountPath: /docker-entrypoint.d/
            {{- end }}
{{- if .Values.dind.enabled }}
        - name: dind
          image: {{ .Values.dind.image | default "docker:19.03-dind" }}
          securityContext:
            privileged: true
          env:
          - name: DOCKER_TLS_CERTDIR
            value: ""
          volumeMounts:
          - name: "docker-graph-storage"
            mountPath: "/var/lib/docker"
          - name: shared-volume
            mountPath: "/var/buildkite"
{{- end }}
{{- if .Values.podContainers }}{{ toYaml .Values.podContainers | nindent 8 }}{{- end }}
      volumes:
{{- if .Values.volumes }}{{ toYaml .Values.volumes | nindent 8 }}{{- end }}
{{- if .Values.enableHostDocker }}
        - name: var-run-docker-sock
          hostPath:
            path: /var/run/docker.sock
{{- end }}
        {{- if .Values.registryCreds.gcrServiceAccountKey }}
        - name: service-key
          secret:
            secretName: {{ template "fullname" . }}-gcr
        {{- end }}
        {{- if .Values.registryCreds.dockerConfig }}
        - name: docker-config
          secret:
            secretName: {{ template "fullname" . }}-registry
        {{- end }}
        {{- if .Values.dind.enabled }}
        - name: docker-graph-storage
          emptyDir: {}
        - name: shared-volume
          emptyDir: {}
        {{- end }}
        {{- if .Values.entrypointd }}
        - name: entrypointd
          configMap:
            name: {{ template "fullname" . }}-entrypointd
            defaultMode: 0777
        {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
{{- end }}
